export const runDetailStyles = `
  .run-module .mem-content-document .mem-content-flow-label.run-current-step-marker{background:var(--accent);color:var(--surface);white-space:nowrap}
  .run-module .run-detail-content{position:relative;padding-top:30px}.run-module .run-disclosure-toggle-all{position:absolute;top:0;right:0;border:0;border-radius:5px;background:transparent;color:var(--muted);padding:4px 7px;font-size:11px}.run-module .run-disclosure-toggle-all:hover{background:var(--soft);color:var(--text)}.run-module .run-disclosure-toggle-all:focus-visible{outline:2px solid #286c672e;outline-offset:1px}
  .run-module details.run-collapsible>summary{cursor:pointer;list-style:none}.run-module details.run-collapsible>summary::-webkit-details-marker{display:none}.run-module .run-disclosure-summary{position:relative}.run-module .run-disclosure-summary:before{content:"›";display:inline-block;flex:none;margin-right:5px;color:var(--muted);font-size:15px;line-height:1;transition:transform .12s ease}.run-module details.run-collapsible[open]>.run-disclosure-summary:before{transform:rotate(90deg)}.run-module .run-disclosure-summary:focus-visible{outline:2px solid #286c672e;outline-offset:2px}.run-module .run-disclosure-body{min-width:0;margin-top:9px}
  .run-module .block-title{margin:12px 0 7px;font-weight:750}.run-module .call-link{min-width:0;color:var(--accent);font-weight:700;overflow-wrap:anywhere}.run-module .task-result{min-width:0;max-width:100%;margin-top:11px;padding:11px;border:1px solid var(--line);border-radius:7px;background:#fafbf8}.run-module .task-result h3{margin:0;font-size:15px}.run-module .run-artifact-summary{display:grid;grid-template-columns:minmax(0,1fr);gap:6px}.run-module .run-artifact-summary:before{position:absolute;right:0;top:4px}.run-module .task-result .artifact-meta-line{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}.run-module .task-result .artifact-meta-line>.run-pill{white-space:normal;overflow-wrap:anywhere;max-width:100%;height:auto}
  .run-module .effective-rule-tree{min-width:0;margin-top:10px}.run-module .effective-rule-tree>.run-disclosure-summary{display:flex;align-items:center;width:max-content;max-width:100%;margin:0;padding:3px 4px;border-radius:5px;color:var(--muted)}.run-module .effective-rule-tree>.run-disclosure-summary:hover{background:var(--soft);color:var(--text)}.run-module .effective-rule-list>.effective-reference-item{white-space:normal}.run-module .section{min-width:0}.run-module .section-header{display:flex;width:100%;min-width:0;align-items:center;gap:6px;border:0;background:transparent;padding:5px 0;text-align:left;color:inherit}.run-module .section-header .chevron{transition:transform .15s}.run-module .section-header[aria-expanded=true] .chevron{transform:rotate(90deg)}.run-module .section-body{min-width:0;padding-left:16px}.run-module .effective-reference>.section-header{font-weight:650}.run-module .effective-section{margin:5px 0;padding-left:8px;border-left:2px solid var(--line)}
  .run-module .run-bindings{padding:0;overflow:hidden}.run-module .run-binding-body{padding:0 20px 18px}.run-module .run-binding-row{display:grid;gap:8px;min-width:0;margin-top:10px;padding:10px;border-top:1px solid var(--line)}.run-module .run-binding-actors{display:flex;flex-wrap:wrap;gap:8px 14px}.run-module .run-binding-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.run-module .run-binding-history{overflow-wrap:anywhere}
  .run-module .schema-writing{min-width:0;margin-top:10px;padding-top:8px;border-top:1px solid var(--line)}.run-module .schema-writing>.run-disclosure-summary{display:flex;align-items:center;width:max-content;max-width:100%;margin:0;padding:3px 4px;border-radius:5px;color:var(--muted)}.run-module .schema-writing-progress{display:flex;gap:6px;flex-wrap:wrap}.run-module .schema-writing-source{min-width:0;margin-top:10px;padding-left:12px;border-left:2px solid var(--line)}.run-module .schema-draft-preview{min-width:0;margin-top:10px}.run-module .schema-draft-path{overflow-wrap:anywhere}.run-module .artifact-review-artifact-content{min-width:0;max-width:100%;overflow-wrap:anywhere}.run-module .artifact-review-artifact-content .markdown-table-scroll,.run-module .artifact-review-artifact-content table{display:block;max-width:100%;overflow-x:auto}.run-module .artifact-review-artifact-content img,.run-module .artifact-review-artifact-content pre{max-width:100%}
  @media(max-width:820px){.run-module .run-binding-actions{align-items:flex-start;flex-direction:column}}
`;
