export const runDetailStyles = `
  .run-module .block-title{margin:12px 0 7px;font-weight:750}.run-module .flow-head{display:grid;grid-template-columns:max-content minmax(0,1fr);gap:8px 12px;align-items:start;min-width:0}.run-module .flow-head>.artifact-row{grid-column:2;min-width:0}
  .run-module .flow-label{display:inline-flex;align-items:center;justify-content:center;min-width:52px;padding:3px 7px;border-radius:999px;background:#e8eeea;color:#49615d;font-size:11px;font-weight:750}.run-module .flow-action{min-width:0;margin:1px 0;font-size:15px;overflow-wrap:anywhere}.run-module .flow-item.call{display:flex;align-items:center;flex-wrap:wrap;gap:9px;border-left:4px solid var(--accent);background:#f2f8f6}.run-module .flow-item.branch{border-left:4px solid #bb8238;background:#fbf7f0}
  .run-module .flow-children{display:grid;gap:8px;min-width:0;margin:10px 0 0 22px;padding-left:12px;border-left:1px solid var(--line)}.run-module .flow-else{min-width:0;margin-top:10px}.run-module .call-link{min-width:0;color:var(--accent);font-weight:700;overflow-wrap:anywhere}.run-module .task-result{min-width:0;max-width:100%;margin-top:11px;padding:11px;border:1px solid var(--line);border-radius:7px;background:#fafbf8}.run-module .task-result h3{margin:0 0 7px}
  .run-module .effective-rule-tree{min-width:0;margin-top:10px}.run-module .text-list{margin:6px 0;padding-left:23px}.run-module .effective-rule-list>.effective-reference-item{white-space:normal}.run-module .section{min-width:0}.run-module .section-header{display:flex;width:100%;min-width:0;align-items:center;gap:6px;border:0;background:transparent;padding:5px 0;text-align:left;color:inherit}.run-module .section-header .chevron{transition:transform .15s}.run-module .section-header[aria-expanded=true] .chevron{transform:rotate(90deg)}.run-module .section-body{min-width:0;padding-left:16px}.run-module .effective-reference>.section-header{font-weight:650}.run-module .effective-section{margin:5px 0;padding-left:8px;border-left:2px solid var(--line)}
  .run-module .run-bindings{padding:0;overflow:hidden}.run-module .run-binding-body{padding:0 20px 18px}.run-module .run-binding-row{display:grid;gap:8px;min-width:0;margin-top:10px;padding:10px;border-top:1px solid var(--line)}.run-module .run-binding-actors{display:flex;flex-wrap:wrap;gap:8px 14px}.run-module .run-binding-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.run-module .run-binding-history{overflow-wrap:anywhere}
  .run-module .schema-writing{min-width:0;margin-top:10px;padding-top:8px;border-top:1px solid var(--line)}.run-module .schema-writing-progress{display:flex;gap:6px;flex-wrap:wrap}.run-module .schema-writing-source{min-width:0;margin-top:10px;padding-left:12px;border-left:2px solid var(--line)}.run-module .schema-draft-preview{min-width:0;margin-top:10px}.run-module .schema-draft-path{overflow-wrap:anywhere}.run-module .artifact-review-artifact-content{min-width:0;max-width:100%;overflow-wrap:anywhere}.run-module .artifact-review-artifact-content .markdown-table-scroll,.run-module .artifact-review-artifact-content table{display:block;max-width:100%;overflow-x:auto}.run-module .artifact-review-artifact-content img,.run-module .artifact-review-artifact-content pre{max-width:100%}
  @media(max-width:820px){.run-module .flow-head{grid-template-columns:1fr}.run-module .flow-head>.artifact-row{grid-column:1}.run-module .flow-label{justify-self:start}.run-module .flow-children{margin-left:5px;padding-left:8px}.run-module .run-binding-actions{align-items:flex-start;flex-direction:column}}
`;
